### ISSUE TITLE
Revist UI text

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-popa#140]
- [ ] Get rid of lorem ipsum sentences, paragrapsh
- [ ] Make sure wording is correct

Requires #141

**Comment by phahulin** [comment]
Few more points:
- [ ] Footer says "_2018 POA. All rights reserved._" should this be "_2018 POA **Network**. All rights reserved._"
- [ ] "On register new address" page, the second field is called "Address", also text in (?) says "Enter full address". This may look confusing (to me at least), because other fields (city, state, ...) are also parts of address. Maybe rename it to "Street address" and change the text in (?)
